{% set name = "importlib_metadata" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46fc60c34b6ed7547e2a723fc8de6dc2e3a1173f8423246b3ce497f064e9c3de

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - zipp >=0.3.2
    - pathlib2  # [py2k]
    - contextlib2  # [py2k]
    - configparser  # [py2k]

test:
  imports:
    - importlib_metadata

about:
  home: http://importlib-metadata.readthedocs.io
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary:  A library to access the metadata for a Python package
  doc_url: https://importlib-metadata.readthedocs.io
  dev_url: https://gitlab.com/python-devs/importlib_metadata

extra:
  recipe-maintainers:
    - nehaljwani
    - nicoddemus
