{% set version = "8.7.0" %}

package:
  name: importlib-metadata
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/importlib_metadata/importlib_metadata-{{ version }}.tar.gz
  sha256: d13b81ad223b890aa16c5471f2ac3056cf76c5f10f82d6f9292f0b415f389000

build:
  number: 0
  noarch: python

outputs:
  - name: importlib-metadata
    script: build_base.sh
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm !=6.1.0,<=8.3.0  # upper constrain to avoid circular dependencies
      run:
        - python >={{ python_min }}
        - zipp >=0.5
    test:
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check
      imports:
        - importlib_metadata

  - name: importlib_metadata
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('importlib-metadata', max_pin="x.x.x") }}
    test:
      imports:
        - importlib_metadata

about:
  home: https://github.com/python/importlib_metadata
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library to access the metadata for a Python package

extra:
  recipe-maintainers:
    - nehaljwani
    - nicoddemus
    - marcelotrevisani
