{% set version = "3.3.0" %}

package:
  name: importlib-metadata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-{{ version }}.tar.gz
  sha256: 5c5a2720817414a6c41f0a49993908068243ae02c1635a228126519b509c8aed

build:
  number: 2

outputs:
  - name: importlib-metadata
    script: build_base.sh
    requirements:
      host:
        - python
        - pip
        - setuptools_scm
      run:
        - python
        - typing_extensions >=3.6.4  # [py<38]
        - zipp >=0.5
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - importlib_metadata

  - name: importlib_metadata
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('importlib-metadata', max_pin="x.x.x") }}
    test:
      imports:
        - importlib_metadata

about:
  home: https://github.com/python/importlib_metadata
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library to access the metadata for a Python package

extra:
  recipe-maintainers:
    - nehaljwani
    - nicoddemus
    - marcelotrevisani
